100-hours-a-week/21-iceT-be

.idea/dataSources/b53a4fef-5b2d-4b59-9404-b62a8acb23ae.xml, .idea/modules.xml, .idea/modules/Koco.main.iml, .idea/workspace.xml, Koco/build.gradle, Koco/src/main/java/icet/koco/KocoApplication.java, Koco/src/main/java/icet/koco/auth/controller/AuthController.java, Koco/src/main/java/icet/koco/auth/dto/AuthResponse.java, Koco/src/main/java/icet/koco/auth/dto/KakaoCallbackRequest.java, Koco/src/main/java/icet/koco/auth/dto/KakaoTokenResponse.java, Koco/src/main/java/icet/koco/auth/dto/KakaoUserResponse.java, Koco/src/main/java/icet/koco/auth/dto/LogoutResponse.java, Koco/src/main/java/icet/koco/auth/dto/RefreshRequest.java, Koco/src/main/java/icet/koco/auth/dto/RefreshResponse.java, Koco/src/main/java/icet/koco/auth/repository/OAuthRepository.java, Koco/src/main/java/icet/koco/auth/service/AuthService.java, Koco/src/main/java/icet/koco/auth/service/KakaoOAuthClient.java, Koco/src/main/java/icet/koco/auth/service/LogoutService.java, Koco/src/main/java/icet/koco/config/SecurityConfig.java, Koco/src/main/java/icet/koco/global/dto/ErrorResponse.java, Koco/src/main/java/icet/koco/global/exception/ForbiddenException.java, Koco/src/main/java/icet/koco/global/exception/GlobalExceptionHandler.java, Koco/src/main/java/icet/koco/global/exception/ResourceNotFoundException.java, Koco/src/main/java/icet/koco/global/exception/UnauthorizedException.java, Koco/src/main/java/icet/koco/problemSet/entity/Solution.java, Koco/src/main/java/icet/koco/user/repository/UserRepository.java, Koco/src/main/java/icet/koco/util/JwtTokenProvider.java, Koco/src/main/resources/application.properties
- Kakao OAuth 2.0 인증 기반 로그인/로그아웃/AccessToken 재발급 기능 구현
- AccessToken은 쿠키(HttpOnly)에, RefreshToken은 DB+Redis에 저장
- 토큰 만료 시 RefreshToken을 통해 자동 재발급 처리
- #5 
- `AuthService`
- `loginWithKakao()` 구현: code → 사용자 정보 조회 → JWT 발급 → 쿠키/DB 저장
- `refreshAccessToken()` 구현: refreshToken 검증 후 accessToken 재발급
- `logout()` 구현: 쿠키 제거 + Redis/DB RefreshToken 삭제
- `JwtTokenProvider`
- JWT 생성/파싱/검증 메서드 구현
- 만료시간 설정 (AccessToken: 30분 / RefreshToken: 14일)
- Redis 사용을 위한 `RedisTemplate` 설정 적용
- 이후 프론트 도메인 확정 시 redirectUrl 수정 필요
- 토큰 만료 시간과 쿠키 유효 시간 동기화가 적절한지 확인 부탁드립니다.
- RefreshToken 저장을 Redis + DB 이중으로 하는 방식이 과한지 검토 부탁드립니다.
- 보안을 위해 RefreshToken을 통해서 재발급할 때 발급받은 IP와 같은지 확인하는 과정이 추가적으로 필요할지 검토 부탁드립니다.
- 현재 모든 요청, 응답에 대해서 Dto class를 다 만들고 있는데 너무 불필요한 작업인지 피드백 부탁드립니다. 
- [Kakao REST …
=> [Feat] 카카오 OAuth를 통한 로그인 및 최초 사용자 등록 기능 구현 (#5)

.idea/workspace.xml, Koco/src/main/java/icet/koco/problemSet/controller/SurveyController.java, Koco/src/main/java/icet/koco/problemSet/dto/ProblemSetSurveyRequestDto.java, Koco/src/main/java/icet/koco/problemSet/dto/ProblemSurveyRequestDto.java, Koco/src/main/java/icet/koco/problemSet/dto/SurveyResponseDto.java, Koco/src/main/java/icet/koco/problemSet/repository/ProblemSetProblemRepository.java, Koco/src/main/java/icet/koco/problemSet/service/ProblemSetService.java, Koco/src/main/java/icet/koco/problemSet/service/SurveyService.java
- `POST /api/v1/problem-set/surveys` API로 출제 문제집에 대한 사용자 설문 응답 기능을 구현했습니다.
- #9 
- `submitSurvey()`에서 문제와 문제집 매핑 검증 방식이 적절한지 확인 부탁드립니다.
=> [Feat] 문제집 설문 응답 기능 구현 (#9)

.idea/workspace.xml, Koco/src/main/java/icet/koco/auth/controller/AuthController.java, Koco/src/main/java/icet/koco/auth/service/AuthService.java, Koco/src/main/java/icet/koco/auth/service/KakaoOAuthClient.java, Koco/src/main/java/icet/koco/auth/service/LogoutService.java, Koco/src/main/java/icet/koco/config/SecurityConfig.java, Koco/src/main/java/icet/koco/config/WebClientConfig.java, Koco/src/main/java/icet/koco/problemSet/controller/SurveyController.java, Koco/src/main/java/icet/koco/problemSet/service/ProblemSetService.java, Koco/src/main/java/icet/koco/problemSet/service/SurveyService.java, Koco/src/main/java/icet/koco/user/controller/UserController.java, Koco/src/main/java/icet/koco/user/repository/UserRepository.java, Koco/src/main/java/icet/koco/user/service/UserService.java, Koco/src/main/java/icet/koco/util/CookieUtil.java, Koco/src/main/java/icet/koco/util/TokenExtractor.java
- Kakao 소셜 로그인을 사용하는 사용자의 탈퇴 기능을 구현
- 추후에 복구 / 접근할 수 있도록 SoftDelete로 구현하면서 Kakao와 Unlink를 수행
- #12 
- `UserService.deleteUser()` 메서드 추가
→ 사용자를 `deletedAt` 기준으로 soft delete 처리
- `OAuthRepository.findByUserId()` 사용
→ Kakao 사용자 unlink 처리를 위해 OAuth 정보 조회
- `KakaoOAuthClient.unlinkUser()` 로직 개선
→ WebClient를 통한 unlink API 호출 구현
- `UserController`에 `DELETE /api/v1/users/me` 엔드포인트 추가
→ 로그인된 사용자 쿠키 기반 토큰을 검증 후 탈퇴 처리 수행
- `WebClientConfig` 클래스 추가
→ Kakao API 호출용 WebClient Bean 등록으로 성능 및 재사용성 개선
- 사용자 탈퇴 후 재가입 시 '신규 가입자' 처리가 아니라 '**복구**'하는 방식으로 구현하였습니다.
- Kakao OAuth 2.0 로직이 구현한 코드와 맞는지 확인 부탁드립니다.
- `KakaoOAuthClient.unlinkUser()`의 WebClient 설정 방식이 적절한지 확인 부탁드립니다.
=> [Feat] 사용자 탈퇴 기능 구현 (#12)

Koco/src/main/java/icet/koco/problemSet/controller/ProblemSetController.java, Koco/src/main/java/icet/koco/problemSet/controller/SolutionController.java, Koco/src/main/java/icet/koco/problemSet/dto/AiSolutionRequestDto.java, Koco/src/main/java/icet/koco/problemSet/dto/ProblemSolutionResponseDto.java, Koco/src/main/java/icet/koco/problemSet/repository/ProblemRepository.java, Koco/src/main/java/icet/koco/problemSet/repository/SolutionRepository.java, Koco/src/main/java/icet/koco/problemSet/service/ProblemSetService.java, Koco/src/main/java/icet/koco/problemSet/service/SolutionService.java
- AI 서버와 연결하는 Endpoint 생성
- 문제 해설 조회 기능 API 구현
- #10 
- AI 서버와 테스트 필요
=> [Feat] 문제 해설 조회 기능 API 구현 (#10)

Koco/src/main/java/icet/koco/auth/controller/AuthController.java, Koco/src/main/java/icet/koco/config/SecurityConfig.java, Koco/src/main/java/icet/koco/global/exception/GlobalExceptionHandler.java, Koco/src/main/java/icet/koco/problemSet/controller/ProblemSetController.java, Koco/src/main/java/icet/koco/problemSet/controller/SolutionController.java, Koco/src/main/java/icet/koco/problemSet/controller/SurveyController.java, Koco/src/main/java/icet/koco/problemSet/entity/Survey.java, Koco/src/main/java/icet/koco/problemSet/repository/SurveyRepository.java, Koco/src/main/java/icet/koco/problemSet/repository/SurveyRepositoryCustom.java, Koco/src/main/java/icet/koco/problemSet/repository/impl/SurveyRepositoryImpl.java, Koco/src/main/java/icet/koco/user/controller/UserController.java, Koco/src/main/java/icet/koco/user/dto/DashboardResponseDto.java, Koco/src/main/java/icet/koco/user/dto/UserCategoryStatDto.java, Koco/src/main/java/icet/koco/user/dto/UserCategoryStatProjection.java, Koco/src/main/java/icet/koco/user/entity/UserAlgorithmStats.java, Koco/src/main/java/icet/koco/user/entity/UserDetail.java, Koco/src/main/java/icet/koco/user/repository/UserAlgorithmStatsRepository.java, Koco/src/main/java/icet/koco/user/repository/UserRepository.java, Koco/src/main/java/icet/koco/user/service/UserAlgorithmStatsService.java, Koco/src/main/java/icet/koco/user/service/UserService.java, Koco/src/main/resources/application.properties
- 메인페이지에서 보이는 대시보드 조회 API를 구현함
- #13 
- 오늘 날짜에 해당하는 `problemSet` 에 대한 설문 페이지로 바로 갈 수 있도록 날짜를 쿼리 파라미터로 받음
- 만약 해당 `problemSet`이 없으면 `TodayProblemSet`은 null 반환
- `ProblemSetProblemRepository`에서 `ProblemSetId`로 문제 목록을 조회하도록 메서드 추가
- `UserAlgorithmStatsRepository`에서 상위 5개 정답률 카테고리 조회 쿼리 작성
=> [Feat] 유저 대시보드 API 구현 (#13)

.idea/dataSources/b53a4fef-5b2d-4b59-9404-b62a8acb23ae.xml, Koco/src/main/java/icet/koco/auth/service/KakaoOAuthClient.java, Koco/src/main/java/icet/koco/config/WebClientConfig.java
- WebClient BaseUrl 변경
- #22 
- redirectUrl 불일치 확인하니 baseUrl로 타 url이 들어가 있어 변경함
=> [Chore] WebClient BaseUrl 변경 (#22)

Koco/src/main/java/icet/koco/auth/controller/AuthController.java
- refresh_token 만료 시 401 Error
- #31 
- Unauthorized로 변경
=> [Chore] 401 에러 추가 (#31)

.gitignore, Koco/src/main/java/icet/koco/problemSet/dto/ProblemDto.java, Koco/src/main/java/icet/koco/problemSet/dto/ProblemSolutionResponseDto.java, Koco/src/main/java/icet/koco/problemSet/service/ProblemSetService.java, Koco/src/main/java/icet/koco/user/controller/UserController.java, Koco/src/main/java/icet/koco/user/dto/UserAlgorithmStatsResponseDto.java, Koco/src/main/java/icet/koco/user/dto/UserInfoResponseDto.java, Koco/src/main/java/icet/koco/user/service/UserService.java
=> [Enhancement] 대시보드 조회 API 분리 (#30)

Koco/src/main/java/icet/koco/util/JwtAuthenticationFilter.java, Koco/src/main/java/icet/koco/util/JwtTokenProvider.java
- JWT를 통한 사용자 인증 처리 필터 구현
- #35 
- JwtAuthenticationFilter 클래스 구현
- 유효하지 않거나 만료된 토큰에 대해 401 응답 반환
- Redis를 통해 토큰 블랙리스트("BL:" + token) 검사
- 토큰 유효성 검사 실패 또는 블랙리스트된 토큰에 대해서는 JSON 에러 메시지와 함께 요청 중단
=> [Fix] 토큰 만료 시 401 에러 반환 (#35)

Koco/build.gradle, Koco/src/main/resources/apllication-prod.yml, Koco/src/main/resources/application-local.yml, Koco/src/main/resources/application.yml, Koco/src/main/resources/logback-spring.xml
- 로컬 작업 시 디스코드 오류 전송 X
- #44 
- 로컬에서 SpringBoot 애플리케이션 실행 시 Error봇 작동 X
=> [Chore] 로컬에서 작업 시 디스코드 알람 가지 않는 기능 수정 (#44)

Koco/build.gradle, Koco/src/main/java/icet/koco/config/SecurityConfig.java
- Health Check API
- close #51 
- [Spring Boot Actuator의 헬스체크 살펴보기](https://toss.tech/article/how-to-work-health-check-in-spring-boot-actuator)
- [Spring Docs](https://docs.spring.io/spring-boot/docs/3.0.5/reference/html/actuator.html#actuator.endpoints.health)
=> [Chore] Health Check API (#51)

Koco/src/main/java/icet/koco/user/controller/UserController.java, Koco/src/main/java/icet/koco/user/dto/UserInfoRequestDto.java, Koco/src/main/java/icet/koco/user/dto/UserInfoResponseDto.java, Koco/src/main/java/icet/koco/user/service/UserService.java
- 유저 정보 등록 및 수정 API의 요청 방식을 @RequestParam → @RequestBody로 변경
- PATCH 방식의 유저 정보 수정 API 구현
- #55 
- 변경사항
- 기존 `@RequestParam` 방식으로 개별 필드를 받던 유저 등록 API를 `@RequestBody`로 통합
- PATCH /users/me 요청 시 JSON에서 포함된 필드만 반영되도록 서비스 로직 수정
- 변경 이유
- RESTful한 API 스타일을 따르기 위해 Body 기반 요청 방식으로 일원화
- 선택적 필드 업데이트가 가능하도록 하여 유연한 사용자 정보 수정 기능 제공
=> [Chore] 회원 정보 등록 RequestParam에서 RequestBody로 변경 (#55)

Koco/src/main/java/icet/koco/auth/service/AuthService.java, Koco/src/main/java/icet/koco/util/JwtAuthenticationFilter.java, Koco/src/main/java/icet/koco/util/JwtTokenProvider.java
[Feat] 회원가입 기능 구현 (#이슈번호)
- accessToken이 만료된 경우에도 refreshToken을 사용한 재발급 요청(/api/backend/v1/auth/refresh)이 정상 처리되도록 필터 예외 처리를 추가
- #이슈번호
- 여러 개 연관 시 모두 명시
- JwtAuthenticationFilter 클래스에 shouldNotFilter() 메서드를 오버라이드하여 /api/backend/v1/auth/refresh 요청에 대해서는 accessToken 검증 로직을 건너뛰도록 처리
- 기존에는 accessToken이 만료되면 무조건 401 응답이 발생해 refreshToken 기반 재발급 요청도 실패함 → 토큰 갱신 로직 동작 불가
- 리뷰어에게 특별히 확인받고 싶은 부분이 있으면 작성
- ex) "메서드 네이밍을 더 직관적으로 만들고 싶은데 조언 부탁드립니다."
- [Spring Security - OncePerRequestFilter 공식 문서](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/filter/OncePerRequestFilter.html)
=> [Fix] accessToken 만료 시 refreshToken 재발급 요청 실패 수정 (#35)

Koco/src/main/java/icet/koco/auth/controller/AuthController.java, Koco/src/main/java/icet/koco/auth/service/AuthService.java, Koco/src/main/java/icet/koco/util/JwtAuthenticationFilter.java, Koco/src/main/java/icet/koco/util/test/TestJwtGenerator.java, Koco/src/main/resources/application.properties
- JWT 기반 인증 필터(`JwtAuthenticationFilter`)를 개선하여 Authorization 헤더 방식 지원 추가
- JMeter 부하테스트용 더미 유저 AccessToken/RefreshToken 대량 발급(200명) CSV 생성 기능 추가
- 기존 쿠키 방식 외 Authorization 헤더 방식으로도 토큰 전송 가능하도록 로직 개선
- #71 
- `JwtAuthenticationFilter`: Authorization 헤더에서 Bearer 토큰 추출 처리 추가  
→ Postman, JMeter 등 헤더 기반 테스트 툴 사용 시 편의성 개선
- `JwtTokenProvider`: Access/RefreshToken 생성 로직 보강, secret 키 길이 점검
- `TestJwtGenerator`: 다수 유저의 Access/RefreshToken을 대량으로 발급하고 CSV로 저장하는 기능 구현  
→ 부하테스트용 JMeter 연동 데이터 파일 제공
=> [Chore]JWT 필터 개선 및 부하테스트용 Access/Refresh Token 발급 (#71)

Koco/src/main/java/icet/koco/problemSet/dto/ProblemSurveyRequestDto.java, Koco/src/main/java/icet/koco/problemSet/repository/SurveyRepository.java, Koco/src/main/java/icet/koco/user/repository/UserAlgorithmStatsRepository.java, Koco/src/main/java/icet/koco/user/service/UserService.java
- 회원 탈퇴 시 해당 사용자의 설문 응답 & 알고리즘 스탯 삭제
- close #102 
- @Query, @Modifying을 이용하여 사용자의 알고리즘 통계 및 설문을 hard delete하는 쿼리 작성
=> [Fix] 회원 탈퇴 시 해당 사용자의 설문 응답 & 알고리즘 스탯 삭제 (#102)

Koco/src/main/java/icet/koco/problemSet/dto/ProblemSurveyRequestDto.java, Koco/src/main/java/icet/koco/problemSet/service/SurveyService.java, Koco/src/main/java/icet/koco/user/service/UserAlgorithmStatsService.java
-  사용자 알고리즘 스탯 재갱신 안됨 문제 해결
- #113 
- DTO의 `boolean` 타입을 `Boolean`으로 변경함
- 변경 이유
- DTO 역직렬화 문제 (Jackson -> DTO) 
- boolean(기본형)은 DTO에서 builder로 넘어갈 때 null이면 false로 처리됨
- 그렇기에 builder를 통해서 생성된 데이터 값에 false가 들어가면서 사용자의 알고리즘 스탯이 갱신이 되지 않고 있었음
=> [Fix] 사용자 알고리즘 스탯 재갱신 안됨 (#113)

Koco/src/main/java/icet/koco/config/SecurityConfig.java, Koco/src/main/java/icet/koco/util/JwtAuthenticationFilter.java, Koco/src/main/java/icet/koco/util/test/TestAuthController.java, Koco/src/main/resources/application.properties
- 개발 서버의 타임존 확인을 위해 타임존 확인 API 추가 구현
- #117 
- application.properties에 jackson.timezone 설정 추가
- 타임존 확인 API 구현
=> [Fix] 타임존 불일치 오류 해결 (#117)

Koco/src/main/java/icet/koco/util/JwtAuthenticationFilter.java
- `JwtAuthenticationFilter`의 `shouldNotFilter` 로직에 `/api/backend/v1/solution` 경로를 토큰 검증 제외 대상에 추가
- CLOSE #121 
- AI 서버로부터 오는 해설 저장 API(/api/backend/v1/solution)는 별도의 인증 토큰 없이 호출되어야 하는데, 현재 필터가 이 경로에도 토큰 검증을 적용하여 500 에러가 발생하거나 요청이 차단됨
- 해당 경로를 예외 처리함으로써 AI → 백엔드 간 연동이 정상적으로 이루어지도록 수정함
=> [Fix] ShouldNotFilter에 solution 경로 추가 (#121)

Dockerfile
hotfix(docker): echo로 scouter.conf 생성 방식 수정하여 문자열 인용 오류 해결
- Dockerfile: here-doc/printf 대신 echo + escape sequence 사용
- net_collector_* 설정이 올바르게 파일에 작성되도록 수정
---
RUN mkdir -p /opt/scouter/agent.java/conf && \
echo 'net_collector_ip=10.1.3.100\n\
net_collector_udp_port=6100\n\
net_collector_tcp_port=6100' > /opt/scouter/agent.java/conf/scouter.conf
=> [HOTFIX] Dockerfile scouter.conf 생성 echo 명령 인용 오류 수정

Dockerfile
호스트 에이전트의 scouter.conf에 설정된 컬렉터 IP가 10.1.3.100으로 되어 있던 것을 Java 에이전트와 동일한 10.3.3.100으로 수정했습니다.
=> [HOTFIX] 호스트 에이전트 collector IP를 10.3.3.100으로 변경

Koco/src/main/java/icet/koco/chatbot/client/FeedbackSseClientImpl.java, Koco/src/main/java/icet/koco/chatbot/client/InterviewSseClientImpl.java, Koco/src/main/java/icet/koco/chatbot/client/MockFeedbackSseClient.java, Koco/src/main/java/icet/koco/chatbot/controller/ChatSessionController.java, Koco/src/main/java/icet/koco/chatbot/entity/ChatSession.java, Koco/src/main/java/icet/koco/chatbot/repository/ChatSessionRepository.java, Koco/src/main/java/icet/koco/chatbot/service/ChatSessionService.java, Koco/src/main/java/icet/koco/chatbot/service/InterviewService.java
[Feat] 회원가입 기능 구현 (#이슈번호)
- 사용자가 선택한 챗봇 세션을 삭제할 수 있도록 하는 백엔드 API를 구현하였습니다.  
- Soft Delete 방식(`deletedAt` 필드 갱신)으로 데이터 정합성과 추후 복구 가능성을 고려했습니다.
- #139
- `ChatSessionController`에 `@DeleteMapping("/session/delete")` API 추가  
- 헤더로 전달된 `Session-Ids`를 파싱하여 사용자의 세션만 필터링하여 soft delete 처리  
- `ChatSessionService` 내 세션 ID 유효성 검사, 사용자 검증, soft delete 로직 추가  
- `finished` 필드 미초기화로 인한 JPA 예외 방지를 위해 해당 필드에 기본값 설정  
- 기존 조회 로직들과 일관성 있게 `deletedAt`이 null인 데이터만 조회되도록 처리 유지
- `Session-Ids`를 Request Header로 받는 방식이 적절한가
=> [Feat] 채팅 세션 삭제 API 구현 (#139)
